### PR TITLE
[Feature] Migrate to Vite

### LINKED ISSUE #508: [feat req] Vite js support
Will be great if the template comes with vite JS support.

### PR DESCRIPTION
**Pull request by paul-phan**
### WHY are these changes introduced?

Resolve #508 

### WHAT is this pull request doing?

Migrate the template to Vite, support HRM, CSS side effect imports.

### Checklist

**Note**: once this PR is merged, it becomes a new release for this template.

- [ ] I have added/updated tests for this change
- [ ] I have made changes to the `README.md` file and other related documentation, if applicable

### CODE REVIEW

**Comment by matteodepalo** [comment]
Hi @paul-phan, thank you for your contribution! We're reviewing this internally and we'll get back to you as soon as possible.

**Comment by paul-phan** [comment]
@blanklob you can try adding `ENV PORT="3000"` to your `Dockerfile`

**Comment by blanklob** [comment]
@paul-phan you are totally right lol thanks yep just migrated https://github.com/Shopify/polaris/releases

Everything is working! thanks

**Comment by blanklob** [comment]
I noticed some issues after switching to vite there is flashing and some styles do not apply.

**Comment by kibertoad** [comment]
@matteodepalo Vite support is finally stable in Remix: https://github.com/remix-run/remix/blob/main/CHANGELOG.md#v270

**Comment by paulomarg** [comment]
We're working on a proper guide, and I'll come back with a link as soon as it's ready.

In the meantime, this is more than the minimal set of changes needed, but [this diff has all the required changes](https://github.com/Shopify/shopify-app-template-remix/compare/dca0bb74fa5933c959f13ca5ec0a67a819829134..64a51c0bda3cbf212afdc33571bd34b51a7e3116).

**Comment by paulomarg** [comment]
Hey folks! We've added some migration instructions in [this wiki page](https://github.com/Shopify/shopify-app-template-remix/wiki/Migrate-your-Remix-app-to-Vite), so it doesn't get copied into new apps.

If you run into any issues applying these, please let me know!

**Comment by blanklob** [comment]
Nice thanks u rock!

**Pull request merged**
