### PR TITLE
Reduce docker image size:

### LINKED ISSUE #720: Docker image can be greatly reduced in size
# Issue summary

Before opening this issue, I have:

- [x] Upgraded to the latest version of the `@shopify` packages
  - Affected `@shopify/shopify-*` package and version:
  - Node version:
  - Operating system:
- [ ] [Not really applicable in this case] Set `{ logger: { level: LogSeverity.Debug } }` in my configuration
- [x] Found a reliable way to reproduce the problem that indicates it's a problem with the package
- [x] Looked for similar issues in this repository
- [x] Checked that this isn't an issue with a Shopify API
  - If it is, please create a post in the [Shopify community forums](https://community.shopify.com/c/partners-and-developers/ct-p/appdev) or report it to [Shopify Partner Support](https://help.shopify.com/en/support/partners/org-select)

I found that the docker image size created in an app built from this template was very large (around 1.7-1.8 GB). I see that there were previous efforts to reduce the image size, such as #418.

After some investigation locally, I found that the issue was a combination of NPM’s cache not being cleared, as well as Docker’s image layer cache.

I'd like to propose a change that reduces the docker image size from ~1.8 GB to ~500 MB. I don't have permission to open a pull request on this repo, so I'm filing this as an issue with info on the solution I found.

## Proposed Change

The key change in the Dockerfile is to modify the `RUN npm install --omit-dev` line to include a clearing of the NPM cache:

```
RUN npm install --omit=dev && npm cache clean --force
```

This will clear the NPM cache, which reduces the overall image size. This needs to be run on the same `RUN` as the `npm install` or else the docker image layer cache will still include the cached data.

I also would propose that the Dockerfile could copy only the package.json and package-lock.json files before the npm install, to allow docker builds to run faster when the only changes made are to application code.

Here are two images I built locally, from this repo, before and after the fix, to demonstrate the savings:

```
$ docker image ls
REPOSITORY                   TAG          IMAGE ID       CREATED          SIZE
shopify-app-template-remix   after-fix    b1a72b194a84   8 seconds ago    522MB
shopify-app-template-remix   before-fix   d1e581de7c98   8 minutes ago    1.81GB
```

Here is the updated Dockerfile I propose:

```
FROM node:18-alpine

EXPOSE 3000

WORKDIR /app

ENV NODE_ENV=production

COPY package.json package-lock.json* ./

RUN npm install --omit=dev && npm cache clean --force
# Remove CLI packages since we don't need them in production by default.
# Remove this line if you want to run CLI commands in your container.
RUN npm remove @shopify/app @shopify/cli

COPY . .

RUN npm run build

# You'll probably want to remove this in production, it's here to make it easier to test things!
RUN rm -f prisma/dev.sqlite

CMD ["npm", "run", "docker-start"]
```

### PR DESCRIPTION
**Pull request by joshuaballoch**
### WHY are these changes introduced?

Fixes #720 . Relates to previous attempts to reduce the file size on #418

* The docker image size for this app is ~ 1.8 GB
* I appears that most of this image size is unnecessary - the actually-used disk space on a running container is much smaller (~500 MB)
* After doing some digging, the main reason for this size is the node modules cache
* It seems like this gets included in the image unless `npm cache clean` gets run
* Additionally, if that line is not run in the same `RUN` as the `npm install`, then it will still show up in the docker image layer cache

### WHAT is this pull request doing?

* This PR proposes adding an `npm cache clean --force` to the `npm install` line
* The proposed strategy reduces image sizes down to ~ 500 MB.
* An additional part of this proposal is to only copy the package.json & lock files before the npm install, which improves docker image layer caching between builds where no dependencies have been changed. This can be removed if preferred.

### Checklist

- [x] I ran this locally to check the docker build still works, plus double-check its image size

```
$ docker image ls
REPOSITORY                   TAG          IMAGE ID       CREATED          SIZE
shopify-app-template-remix   after-fix    b1a72b194a84   8 seconds ago    522MB
shopify-app-template-remix   before-fix   d1e581de7c98   8 minutes ago    1.81GB
```

### CODE REVIEW

**Comment by mufftee** [comment]
Just a quick question.
how would this work if we have a deployment inside the dockerfile?
For example like this?

```
FROM node:22
EXPOSE 3000
WORKDIR /app
COPY . .

ARG SHOPIFY_APP_NAME
ARG SHOPIFY_APP_HANDLE
ARG SHOPIFY_API_KEY
ARG SHOPIFY_APP_URL
ARG SCOPES
ARG SHOPIFY_CLI_PARTNERS_TOKEN
ARG DEPLOY_TYPE

ENV NODE_ENV=production \
  SHOPIFY_APP_NAME=$SHOPIFY_APP_NAME \
  SHOPIFY_APP_HANDLE=$SHOPIFY_APP_HANDLE \
  SHOPIFY_API_KEY=$SHOPIFY_API_KEY \
  APP_URL=$SHOPIFY_APP_URL \
  SCOPES=$SCOPES \
  SHOPIFY_CLI_PARTNERS_TOKEN=$SHOPIFY_CLI_PARTNERS_TOKEN \
  DEPLOY_TYPE=$DEPLOY_TYPE

RUN npm ci
RUN npm run deploy -- -f --config $DEPLOY_TYPE
RUN npm remove @shopify/app @shopify/cli
RUN npm run build

CMD ["npm", "run", "docker-start"]
```

I did try the approach from the PR, but cant figure it out to copy all the needed files for the deploy.

Some advice on this?

**Comment by joshuaballoch** [comment]
Hi @lizkenyon! Thanks for the idea. I read the linked documentation about the `npm ci` command. It seems like a nice idea, but I ran into an issue switching to that which seems to be that the repo doesn't have a `package-lock.json` file. That seems like a blocker to using that command.

Is there a reason that this template doesn't include the lockfile? Here is the output from my local when trying it out:

```
$ docker build . --tag shopify-app-template-remix:latest
[+] Building 6.8s (9/13)                                                                                                                                        docker:desktop-linux
 => [internal] load build definition from Dockerfile                                                                                                                            0.0s
 => => transferring dockerfile: 577B                                                                                                                                            0.0s
 => [internal] load metadata for docker.io/library/node:18-alpine                                                                                                               1.5s
 => [auth] library/node:pull token for registry-1.docker.io                                                                                                                     0.0s
 => [internal] load .dockerignore                                                                                                                                               0.0s
 => => transferring context: 66B                                                                                                                                                0.0s
 => [1/8] FROM docker.io/library/node:18-alpine@sha256:e37da457874383fa9217067867ec85fe8fe59f0bfa351ec9752a95438680056e                                                         4.2s
 => => resolve docker.io/library/node:18-alpine@sha256:e37da457874383fa9217067867ec85fe8fe59f0bfa351ec9752a95438680056e                                                         0.0s
 => => sha256:e37da457874383fa9217067867ec85fe8fe59f0bfa351ec9752a95438680056e 7.67kB / 7.67kB                                                                                  0.0s
 => => sha256:538e4e1286473c79ec415222d2ed61c1112c00056ad7f212ce64c15c908bde41 1.72kB / 1.72kB                                                                                  0.0s
 => => sha256:3bf7cda95541c7c761cae4bbf808f9494681beb4294f59fd18a28196371bcb16 6.36kB / 6.36kB                                                                                  0.0s
 => => sha256:ec99f8b99825a742d50fb3ce173d291378a46ab54b8ef7dd75e5654e2a296e99 3.62MB / 3.62MB                                                                                  0.3s
 => => sha256:02f3ccc09b42757820c1367e6c2a9236c63fd40f5b320b5e1105c37fb124e8d9 39.83MB / 39.83MB                                                                                1.6s
 => => sha256:e97a1c9d6f0e4fed4f47d45408c60a629ad4c1a0de636ff46ea009e770d8325f 1.38MB / 1.38MB                                                                                  0.5s
 => => extracting sha256:ec99f8b99825a742d50fb3ce173d291378a46ab54b8ef7dd75e5654e2a296e99                                                                                       0.2s
 => => sha256:becaece7e20c8ebfa1b1e164d00137f195571e81fd0797c51b334a6e9e1bdcf1 451B / 451B                                                                                      0.6s
 => => extracting sha256:02f3ccc09b42757820c1367e6c2a9236c63fd40f5b320b5e1105c37fb124e8d9                                                                                       2.3s
 => => extracting sha256:e97a1c9d6f0e4fed4f47d45408c60a629ad4c1a0de636ff46ea009e770d8325f                                                                                       0.1s
 => => extracting sha256:becaece7e20c8ebfa1b1e164d00137f195571e81fd0797c51b334a6e9e1bdcf1                                                                                       0.0s
 => [internal] load build context                                                                                                                                               0.0s
 => => transferring context: 33.00kB                                                                                                                                            0.0s
 => [2/8] WORKDIR /app                                                                                                                                                          0.2s
 => [3/8] COPY package.json package-lock.json* ./                                                                                                                               0.0s
 => ERROR [4/8] RUN npm ci --omit=dev && npm cache clean --force                                                                                                                0.7s
------
 > [4/8] RUN npm ci --omit=dev && npm cache clean --force:
0.669 npm error code EUSAGE
0.674 npm error
0.674 npm error The `npm ci` command can only install with an existing package-lock.json or
0.674 npm error npm-shrinkwrap.json with lockfileVersion >= 1. Run an install with npm@5 or
0.674 npm error later to generate a package-lock.json file, then try again.
0.674 npm error
0.674 npm error Clean install a project
0.674 npm error
0.674 npm error Usage:
0.674 npm error npm ci
0.674 npm error
0.674 npm error Options:
0.674 npm error [--install-strategy <hoisted|nested|shallow|linked>] [--legacy-bundling]
0.674 npm error [--global-style] [--omit <dev|optional|peer> [--omit <dev|optional|peer> ...]]
0.674 npm error [--include <prod|dev|optional|peer> [--include <prod|dev|optional|peer> ...]]
0.674 npm error [--strict-peer-deps] [--foreground-scripts] [--ignore-scripts] [--no-audit]
0.674 npm error [--no-bin-links] [--no-fund] [--dry-run]
0.674 npm error [-w|--workspace <workspace-name> [-w|--workspace <workspace-name> ...]]
0.674 npm error [-ws|--workspaces] [--include-workspace-root] [--install-links]
0.674 npm error
0.674 npm error aliases: clean-install, ic, install-clean, isntall-clean
0.674 npm error
0.674 npm error Run "npm help ci" for more info
0.676
0.676 npm error A complete log of this run can be found in: /root/.npm/_logs/2024-06-26T08_31_54_178Z-debug-0.log
------
Dockerfile:11
--------------------
   9 |     COPY package.json package-lock.json* ./
  10 |
  11 | >>> RUN npm ci --omit=dev && npm cache clean --force
  12 |     # Remove CLI packages since we don't need them in production by default.
  13 |     # Remove this line if you want to run CLI commands in your container.
--------------------
ERROR: failed to solve: process "/bin/sh -c npm ci --omit=dev && npm cache clean --force" did not complete successfully: exit code: 1
```

**Comment by lizkenyon** [comment]
Thanks for trying this out @muchisx! 
Glad to hear that it worked well!

At this time we want to keep supporting Node 18. But I am glad to hear you were able to upgrade and are using the latest version of Polaris for your project.

We have actually [removed](https://github.com/Shopify/shopify-app-template-remix/pull/781) the `@shopify/app` dependency. So this could be removed entirely. 
The CLI dependency will also now only be there for new apps that are **not** created with the global CLI.

I believe you are right that we could move the removal of the CLI before the installation.

**Comment by joshuaballoch** [comment]
@lizkenyon I've updated the proposed changes with the switch to `npm ci`. I also removed the now-unnecessary reference to `@shopify/app`.

I have left out the switch of putting the `npm remove` step earlier than the `npm install`. I found that moving this earlier results in a larger docker image. Perhaps there is a solution for that that someone else can look into, in a separate proposal - for the time being, the proposed change results in the smallest image size as I have been able to find up to now.

With this update, is the proposal able to be adopted?

**Review by lizkenyon — APPROVED** [review]

**Pull request merged**
