### PR TITLE
update webhooks organization

### PR DESCRIPTION
**Pull request by TheGreatSimo**
### Why are these changes introduced?

Organizing webhook routes for better maintainability

### What  is this pull request doing?

This PR groups all webhook routes into a dedicated webhooks directory improving organization and clarity

### Test this PR
```
shopify app init --template=https://github.com/TheGreatSimo/shopify-app-template-remix#simo
```
### Checklist

-  I added Remix flat routes to the package.json
- I created a directory for the webhooks and moved the webhook files into this directory
- I updated imports accordingly

### CODE REVIEW

**Comment by Arkham** [comment]
Just a quick question, why is the folder named `webhooks+`? it might be a convention I'm not familiar with :)

**Comment by byrichardpowell** [comment]
Hey @TheGreatSimo 👋 

Thanks so much for the PR.

I personally really like putting all the webhook routes in a single folder.  Unfortunately, I'm a little nervous about adding the  [Remix flat routing package](https://github.com/kiliman/remix-flat-routes) (Even though I like it).  We try to keep the template fairly vanilla Remix, which means avoiding adding packages that aren't what 90% of developers would expect most of the time.  It's a difficult balance because adding something might make the template better for some people, but it might be something that other people want to rip out.  Adding something can also create a disconnect with the official Remix docs too which describe it one way, but the template does it slightly differently.

Can we do this without the [Remix flat routing package](https://github.com/kiliman/remix-flat-routes)?

**Comment by TheGreatSimo** [comment]
Hey @byrichardpowell thank you for your feedback
I’m not sure if there’s another way to organize routes in Remix v2 without it
If you have suggestions I’d really appreciate them otherwise feel free to close the PR if it doesn’t fit

**Comment by byrichardpowell** [comment]
Thanks for understanding @TheGreatSimo :+1:

Unfortunately I'm not aware of another way, so I'll close this PR.  Thanks so much for contributing though. I really appreciate you taking the time to submit this.

**Pull request closed without merging**
