### PR TITLE
[FIX] File path

### PR DESCRIPTION
**Pull request by bayuTiger**
### WHY are these changes introduced?

https://github.com/Shopify/shopify-app-template-remix/pull/757

↑ This change brings the following changes to javascript
https://github.com/Shopify/shopify-app-template-remix/pull/766/files

This is not interpreted correctly by javascript and an error will occur if the specified module is not found

### WHAT is this pull request doing?

As you can see, sir.

### CODE REVIEW

**Comment by vivi-tora** [comment]
I have signed the CLA!

**Comment by bayuTiger** [comment]
https://github.com/Shopify/shopify-app-template-remix/pull/769

**Comment by bayuTiger** [comment]
I have signed the CLA!

**Comment by vivi-tora** [comment]
I have signed the CLA!

**Comment by matteodepalo** [comment]
@bayuTiger thank you for opening this PR. I see in my editor that the path is resolved fine. As this is compiled by vite, the `~` should point to the source directory.
Can you tell me which error are you seeing?

**Comment by bayuTiger** [comment]
@matteodepalo thanks your review.

https://shopify.dev/docs/apps/build/scaffold-app

If you follow the steps in this document to build the sample app, you will get the following error when entering the shopify app dev command

```
[vite] Pre-transform error: Failed to load url ~/shopify.server (resolved id: ~/shopify.server) in
/Users/bayuTiger/test-app/app/routes/webhooks.jsx. Does the file exist?

...

[vite] Internal server error: Cannot find module '~/db.server' imported from
'/Users/bayuTiger/test-app/app/shopify.server.js'
```

**Comment by matteodepalo** [comment]
Apologies for the mistake, for some reason vite isn't picking up `~` correctly. I'll merge your changes, thank you.

**Pull request merged**
